### PR TITLE
Replace incorrect use of getIndex() in EnumValueDescriptor with getNumber()

### LINKED ISSUE #225: Protobuf enums inconsistently use `ordinal` and `getNumber`
In #29 there's an open item to implement more featureful enum handling. However, the [proposal 190](https://github.com/google/cel-spec/wiki/proposal-190) hasn't been approved yet

In the meanwhile, `cel-java` appears to inconsistently use the [ordinal/index of the enum value](https://github.com/projectnessie/cel-java/blob/8e02beb72f08a408b040163f7e86af8b4e9baa9d/core/src/main/java/org/projectnessie/cel/common/types/pb/EnumValueDescription.java#L48) and the [getNumber of the protobuf enum value descriptor](https://github.com/projectnessie/cel-java/blob/75d90ceea7c11d0d9a28ee05804e61da46440e0d/core/src/main/java/org/projectnessie/cel/common/types/pb/FieldDescription.java#L267).

This leads to bugs where the enum values are out of order in the protobuf enum declaration.

### PR DESCRIPTION
**Pull request by rbtying**
Fixes #225 

1. [Best practice for protocol buffers](https://errorprone.info/bugpattern/ProtocolBufferOrdinal) is to use `getNumber` rather than `ordinal` on the generated Java enum (which the `EnumValueDescriptor`'s `getIndex` corresponds to
2. The `cel-go` implementation that `cel-java` is based on uses `getNumber`
3. other parts of `cel-java` use `getNumber`

Note: the test update corrects the test to do the right thing, but it doesn't fail in the existing (incorrect) implementation because the test enum has `getNumber() == getIndex()` for all values.

### CODE REVIEW

File: core/src/test/java/org/projectnessie/cel/common/types/ProviderTest.java [hunk 1]
```diff
@@ -87,12 +88,29 @@ void typeRegistryCopy() {
...
+
+    // Previously, we checked `getIndex` on the `EnumValueDescriptor`, which is the same as the
+    // `ordinal` value on the enum.
+    assertThat(OutOfOrderEnumOuterClass.OutOfOrderEnum.TWO.ordinal())
+        .isEqualTo(OutOfOrderEnumOuterClass.OutOfOrderEnum.TWO.getValueDescriptor().getIndex());
+    // Test the case where the protobuf-defined value for the enum differs from the generated Java
+    // enum's ordinal() function.
+    assertThat(OutOfOrderEnumOuterClass.OutOfOrderEnum.TWO.getNumber())
+        .isNotEqualTo(OutOfOrderEnumOuterClass.OutOfOrderEnum.TWO.ordinal());
+    assertThat(OutOfOrderEnumOuterClass.OutOfOrderEnum.TWO.getNumber())
```
Comment (snazy) [inline core/src/test/java/org/projectnessie/cel/common/types/ProviderTest.java:107]: Nit: you can add the 2nd `.isEqualTo()` directly behind the one in line 106 (aka: remove the semicolon in 106 and remove line 107).

**Review by snazy — COMMENTED** [review]
Thanks! The test looks good - maybe just add anohter value.

**Review by snazy — APPROVED** [review]
Changes LGTM!
Thanks for the fix!
